"""Add preferences to User

Revision ID: 2929ea2dd80d
Revises: 73abfe5e6264
Create Date: 2024-03-21 15:24:03.307027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2929ea2dd80d'
down_revision = '73abfe5e6264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferences')
    # ### end Alembic commands ###
