"""Add role to User

Revision ID: 73abfe5e6264
Revises: 57dc474265a3
Create Date: 2024-03-21 12:18:20.420442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73abfe5e6264'
down_revision = '57dc474265a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=80), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
